### ISSUE TITLE
Redstone bugs.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncRedstone#10]
PaperSpigot dev 958 (MC 1.11)
https://ci.destroystokyo.com/job/PaperSpigot/958/
FAR dev 14
http://ci.athion.net/job/FastAsyncRedstone/14/
FAWE dev 404
http://ci.athion.net/job/FastAsyncWorldEdit/404/
WorldEdit dev 3654
http://builds.enginehub.org/job/worldedit/9600
ProtocolLib dev 335
http://ci.dmulloy2.net/job/ProtocolLib/335/

@boy0001 Updated Spigot and FAR from dev 13 to 14, now getting reports of many redstone bugs.

> Redstone is really bugged right now, was fine last night. Redstone torches are not dropping when you break them nor can their signal be inverted. Pistons when active the top dissapears and they don't work among other things.

> Repeaters aren't working at all, pistons don't work when they are active, and you can't pick up redstone torches.
> even worse: redstonetorches don't invert anymore >.<

>  i just broke 3 pistons and a redstone torch and it just dissapeared?

Removing FAR and going back to PandaWire, everything seems to work fine. :( No errors in console, start-up initialization seems fine.
```
[04:38:21] [Server thread/INFO]: [FastAsyncRedstone] Injecting custom classes
[04:38:22] [Server thread/INFO]: [FastAsyncRedstone] Loading FastAsyncRedstone v1.0
[04:38:22] [Server thread/INFO]: [FastAsyncRedstone] Enabling FastAsyncRedstone v1.0
```

```
optimize-devices:
  redstone-wire: true
  redstone-lamp: true
  lit-redstone-lamp: true
  sticky-piston: true
  piston: true
  unlit-redstone-torch: true
  redstone-torch: true

# Queues cosmetic changes and performs async
#  - Redstone might be alternating every tick
#  - Players don't need to see every change
queue:
  # Configure the interval for the async queue
  #  - Lighting changes are calculated
  #  - Bulk packets are sent
  #  - Increase to reduce CPU usage
  #  - Lower to see changes sooner
  interval: 6
```
