### ISSUE TITLE
Redstone Torch Dupe

### ISSUE THREAD

**Issue by SwiftSwamp** [boy0001/FastAsyncRedstone#14]
There's a dupe with Redstone Torches that lets you infinitely place them after crafting.

* Craft a Redstone Torch
* Place the Redstone Torch via Survival
* Redstone Torch is placed, then respawns back in your infinite (Tested with a debugger, it's not calling block place updates)
* Turning off Redstone Torch Configuration options fixes the problem

Only works with Redstone Torches, tried all of the other Redstone Blocks.

### Configuraiton ###

``` yaml
# These first 6 aren't configurable
issues: "https://github.com/boy0001/FastAsyncRedstone/issues"
wiki: "https://github.com/boy0001/FastAsyncRedstone/wiki/"
date: null
build: null
commit: null
platform: null

optimize-devices:
  redstone-wire: true
  redstone-lamp: true
  lit-redstone-lamp: true
  sticky-piston: true
  piston: true
  unlit-redstone-torch: false
  redstone-torch: false

# Queues cosmetic changes and performs async
#  - Redstone might be alternating every tick
#  - Players don't need to see every change
queue:
  # Configure the interval for the async queue
  #  - Lighting changes are calculated
  #  - Bulk packets are sent
  #  - Increase to reduce CPU usage
  #  - Lower to see changes sooner
  interval: 6
```

FAR Version: FastAsyncRedstone-16.12.03-e31de71-18-0.1.13
FAWE Version: FastAsyncWorldEdit-bukkit-16.12.20-dcc0c15-439-9.21.0
Spigot Version: git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) 532 version(s) behind.
WorldEdit Version: worldedit-bukkit-6.1.7-SNAPSHOT-dist
