### ISSUE TITLE
'null' entries in config.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncRedstone#7]
FastAsyncRedstone dev 10
PaperSpigot dev 933 (MC 1.11)

Missing info similar to FAWE?

```
# These first 6 aren't configurable
issues: "https://github.com/boy0001/FastAsyncRedstone/issues"
wiki: "https://github.com/boy0001/FastAsyncRedstone/wiki/"
date: null
build: null
commit: null
platform: null

optimize-devices:
  redstone-wire: true
  redstone-lamp: true
  lit-redstone-lamp: true
  sticky-piston: true
  piston: true
  unlit-redstone-torch: true
  redstone-torch: true

# Queues cosmetic changes and performs async
#  - Redstone might be alternating every tick
#  - Players don't need to see every change
queue:
  # Configure the interval for the async queue
  #  - Lighting changes are calculated
  #  - Bulk packets are sent
  #  - Increase to reduce CPU usage
  #  - Lower to see changes sooner
  interval: 6
```
